#
# Link the individual programs.
#
#progs: all
#	for i in $(RUNS); do yes Q | ./$$i &> /dev/null || echo $$i fails; done

clique:       clique.o disc.o $(LIBS)
codml:        codml.o ml.o seq.o $(LIBS)
consense:     consense.o cons.o $(LIBS)
contml:       contml.o cont.o ml.o $(LIBS)
contrast:     contrast.o cont.o $(LIBS)
dnacomp:      dnacomp.o seq.o parsimony.o dnaparsimony.o $(LIBS)
dnadist:      dnadist.o pmatrix.o matrixd.o seq.o $(LIBS)
dnainvar:     dnainvar.o seq.o $(LIBS)
dnaml:        dnaml.o seq.o ml.o $(LIBS)
dnamlk:       dnamlk.o seq.o ml.o $(LIBS)
dnamove:      dnamove.o seq.o moves.o parsimony.o dnaparsimony.o $(LIBS)
dnapars:      dnapars.o seq.o parsimony.o dnaparsimony.o $(LIBS)
dnapenny:     dnapenny.o seq.o parsimony.o dnaparsimony.o $(LIBS)
dolmove:      dolmove.o disc.o moves.o dollo.o $(LIBS)
dollop:       dollop.o disc.o dollo.o $(LIBS)
dolpenny:     dolpenny.o disc.o dollo.o $(LIBS)
drawgram:     drawgram.o draw.o draw2.o drawinit.o $(LIBS)
drawtree:     drawtree.o draw.o draw2.o drawinit.o $(LIBS)
factor:       factor.o disc.o $(LIBS)
fitch:        fitch.o dist.o ml.o $(LIBS)
gendist:      gendist.o pmatrix.o $(LIBS)
kitsch:       kitsch.o dist.o ml.o $(LIBS)
mix:          mix.o disc.o wagner.o $(LIBS)
move:         move.o disc.o moves.o wagner.o $(LIBS)
neighbor:     neighbor.o dist.o $(LIBS)
pars:         pars.o discreteparsimony.o parsimony.o $(LIBS)
penny:        penny.o disc.o wagner.o $(LIBS)
proml:        proml.o prom_common.o seq.o ml.o $(LIBS)
promlk:       promlk.o prom_common.o seq.o ml.o $(LIBS)
protdist:     protdist.o seq.o pmatrix.o $(LIBS)
protpars:     protpars.o seq.o parsimony.o $(LIBS)
restdist:     restdist.o rest_common.o seq.o pmatrix.o $(LIBS)
restml:       restml.o rest_common.o seq.o ml.o $(LIBS)
retree:       retree.o moves.o $(LIBS)
seqboot:      seqboot.o seq.o $(LIBS)
threshml:     threshml.o cont.o $(LIBS)
treedist:     treedist.o cons.o $(LIBS)
